a, b, c = input().split()                            
d, e, f = input().split()                            
b= int(b)                                            
c= float(c)                                          
e= int(e)                                            
f= float(f)                                          
print(f'VALOR A PAGAR: R$ {(b*c) + (e*f):.2f}') 